# Generated by Django 4.2.23 on 2025-07-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='emoji',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='token',
            field=models.CharField(default='f3499dba03d9', max_length=12, unique=True),
        ),
    ]
