# Generated by Django 4.2.23 on 2025-07-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_player_emoji_alter_game_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='started',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='token',
            field=models.CharField(default='f6a92f1f5f62', max_length=12, unique=True),
        ),
    ]
