# Generated by Django 4.2.23 on 2025-07-20 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_last_fact_added'),
        ('game', '0003_game_started_alter_game_token'),
    ]

    operations = [
    ]
