# Generated by Django 4.2.23 on 2025-07-20 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_player_ip_address_alter_game_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_fact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_in_games', to='game.fact'),
        ),
        migrations.AlterField(
            model_name='game',
            name='token',
            field=models.CharField(default='fb0b9ce3b8eb', max_length=12, unique=True),
        ),
    ]
