# Generated by Django 4.2.23 on 2025-07-26 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_game_current_fact_alter_game_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='fact',
            name='story_rating_average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fact',
            name='story_rating_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='game_phase',
            field=models.CharField(choices=[('guessing', 'Guessing Phase'), ('storytelling', 'Story Telling Phase'), ('rating', 'Story Rating Phase')], default='guessing', max_length=20),
        ),
        migrations.AddField(
            model_name='game',
            name='story_teller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telling_story_in_games', to='game.player'),
        ),
        migrations.AddField(
            model_name='player',
            name='has_finished_story',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='has_rated_story',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='token',
            field=models.CharField(default='f1946f0f7c60', max_length=12, unique=True),
        ),
        migrations.CreateModel(
            name='LiveGuess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('fact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_guesses', to='game.fact')),
                ('guessed_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guessed_for', to='game.player')),
                ('guesser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_guesses', to='game.player')),
            ],
        ),
        migrations.CreateModel(
            name='StoryRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'Boring'), (2, 'Good'), (3, 'Amazing')])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('fact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_ratings', to='game.fact')),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_ratings', to='game.player')),
            ],
            options={
                'unique_together': {('fact', 'rater')},
            },
        ),
    ]
