# Generated by Django 4.2.23 on 2025-07-26 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_fact_story_rating_average_fact_story_rating_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='token',
            field=models.CharField(default='8b8f16253c65', max_length=12, unique=True),
        ),
        migrations.CreateModel(
            name='ScoreLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('score_type', models.CharField(choices=[('correct_guess', 'Correct Guess'), ('wrong_guesses', 'Wrong Guesses on Fact'), ('story_rating', 'Story Rating Bonus')], max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('fact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.fact')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_logs', to='game.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_logs', to='game.player')),
            ],
        ),
    ]
