# Generated by Django 4.2.23 on 2025-08-01 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_game_token_scorelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='token',
            field=models.CharField(default='4400f64265b1', max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='guessevent',
            name='correct_guesser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correct_guesses', to='game.player'),
        ),
    ]
